import { locale } from '@/i18n'

const apiErrorMessages: Record<string, string> = {
  API_ERROR: 'The server could not complete the request. Please try again.',
  ACTIVE_EXPEDITION_EXISTS: 'An expedition is already active. Finish it before starting another one.',
  AUTH_REQUIRED: 'Please sign in with your wallet before continuing.',
  AUTH_CHALLENGE_EXPIRED: 'The wallet signature request expired. Please try again.',
  AUTH_CHALLENGE_USED: 'That wallet signature request was already used. Please try again.',
  CANNOT_BUY_OWN_LISTING: 'You cannot buy your own market listing.',
  CHAIN_CALL_FAILED: 'The blockchain request failed. Please check the network and try again.',
  CHAIN_PET_MINT_FAILED: 'The starter pet could not be created on-chain. Please try again.',
  CHAIN_PET_MINTER_NOT_CONFIGURED: 'On-chain starter pet creation is not configured on the server yet.',
  CHAIN_PETS_SYNC_FAILED: 'On-chain pet data could not be synced. Please try again.',
  DUPLICATE_PET_IDS: 'Choose each expedition pet only once.',
  EXPEDITION_ALREADY_ACTIVE: 'An expedition is already active. Finish it before starting another one.',
  EXPEDITION_ALREADY_CLAIMED: 'This expedition reward has already been claimed. Refresh your adventure status.',
  EXPEDITION_CLAIM_CONFLICT: 'The reward could not be claimed because the expedition changed. Refresh and try again.',
  EXPEDITION_CREATE_FAILED: 'The expedition could not be started. Please try again.',
  EXPEDITION_LOG_CREATE_FAILED: 'The expedition started, but its log could not be saved. Please refresh.',
  EXPEDITION_LOGS_LOOKUP_FAILED: 'Expedition logs could not be loaded. Please refresh your adventure status.',
  EXPEDITION_LOOKUP_FAILED: 'Expedition status could not be loaded. Please try again.',
  EXPEDITION_NOT_FOUND: 'That expedition could not be found. Refresh your adventure status.',
  EXPEDITION_NOT_FINISHED: 'The expedition is still in progress. Check back when the timer finishes.',
  EXPEDITION_NOT_READY: 'The expedition is still in progress. Check back when the timer finishes.',
  EXPEDITION_WALLET_MISMATCH: 'This expedition belongs to another wallet.',
  FRIEND_ALREADY_EXISTS: 'This wallet is already on your friend list.',
  INSUFFICIENT_MATERIAL: 'You do not have enough of that material.',
  INTERNAL_SERVER_ERROR: 'Something went wrong on the server. Please try again.',
  INVALID_REQUEST: 'Some request details were invalid. Please check your selection and try again.',
  INVALID_AUTH_CHALLENGE: 'The wallet signature request no longer matches. Please try again.',
  INVALID_AUTH_TOKEN: 'Your session expired. Please sign in again.',
  INVALID_SIGNATURE: 'The wallet signature could not be verified. Please try again.',
  INVALID_TOKEN: 'Your session expired. Please sign in again.',
  PET_NOT_OWNED: 'One or more selected pets are not available in your wallet session. Refresh your pets and try again.',
  PETS_LOOKUP_FAILED: 'Pet data could not be checked. Please try again.',
  LISTING_NOT_ACTIVE: 'This listing is no longer active. Refresh the marketplace.',
  MARKET_LISTING_BUY_CONFLICT: 'This listing changed while you were buying it. Refresh the marketplace and try again.',
  MARKET_LISTING_CANCEL_CONFLICT: 'This listing changed while it was being cancelled. Refresh the marketplace and try again.',
  MARKET_LISTING_CREATE_FAILED: 'The listing could not be created. Please try again.',
  MARKET_LISTING_NOT_FOUND: 'This listing no longer exists. Refresh the marketplace.',
  MARKET_LISTING_NOT_OWNED: 'You can only cancel your own market listings.',
  MARKET_LISTINGS_LOOKUP_FAILED: 'Market listings could not be loaded. Please try again.',
  MATERIAL_LISTING_NOT_FOUND: 'This listing no longer exists. Refresh the marketplace.',
  NETWORK_ERROR: 'Backend API is not reachable. Start the backend server and try again.',
  PLAYER_NOT_FOUND: 'Player data could not be found. Please sign in again.',
  PET_LISTING_NOT_FOUND: 'This pet listing no longer exists. Refresh the marketplace.',
  PET_NOT_FOUND: 'That pet could not be found on-chain.',
  TRANSACTION_CREATE_FAILED: 'The market action completed but the transaction record could not be saved. Refresh your activity.',
  TRANSACTIONS_LOOKUP_FAILED: 'Transactions could not be loaded. Please try again.',
  VALIDATION_ERROR: 'Some request details were invalid. Please check your selection and try again.',
  WALLET_PROVIDER_MISSING: 'MetaMask is not installed. Please install or enable MetaMask to continue.',
  WALLET_SIGNATURE_FAILED: 'Wallet signature failed. Please try again.',
  WALLET_TRANSACTION_FAILED: 'Wallet transaction failed. Please try again.',
}

const zhApiErrorMessages: Record<string, string> = {
  API_ERROR: '伺服器無法完成請求，請稍後再試。',
  ACTIVE_EXPEDITION_EXISTS: '目前已有進行中的遠征，請先完成它。',
  AUTH_REQUIRED: '請先用錢包登入。',
  AUTH_CHALLENGE_EXPIRED: '錢包簽名請求已過期，請重新嘗試。',
  AUTH_CHALLENGE_USED: '這次錢包簽名請求已使用過，請重新嘗試。',
  CANNOT_BUY_OWN_LISTING: '不能購買自己上架的商品。',
  CHAIN_CALL_FAILED: '鏈上請求失敗，請確認網路後重試。',
  CHAIN_PET_MINT_FAILED: '初始角色建立失敗，請稍後再試。',
  CHAIN_PET_MINTER_NOT_CONFIGURED: '伺服器尚未設定初始角色建立功能。',
  CHAIN_PETS_SYNC_FAILED: '角色鏈上資料同步失敗，請稍後再試。',
  DUPLICATE_PET_IDS: '每隻遠征角色只能選擇一次。',
  EXPEDITION_ALREADY_ACTIVE: '目前已有進行中的遠征，請先完成它。',
  EXPEDITION_ALREADY_CLAIMED: '這次遠征獎勵已回報過，請重新整理遠征狀態。',
  EXPEDITION_CLAIM_CONFLICT: '遠征狀態已變更，無法回報獎勵，請重新整理後再試。',
  EXPEDITION_CREATE_FAILED: '遠征無法開始，請稍後再試。',
  EXPEDITION_LOG_CREATE_FAILED: '遠征已開始，但紀錄儲存失敗，請重新整理。',
  EXPEDITION_LOGS_LOOKUP_FAILED: '遠征紀錄載入失敗，請重新整理遠征狀態。',
  EXPEDITION_LOOKUP_FAILED: '遠征狀態載入失敗，請稍後再試。',
  EXPEDITION_NOT_FOUND: '找不到這次遠征，請重新整理遠征狀態。',
  EXPEDITION_NOT_FINISHED: '遠征尚未結束，請等倒數完成。',
  EXPEDITION_NOT_READY: '遠征尚未結束，請等倒數完成。',
  EXPEDITION_WALLET_MISMATCH: '這次遠征屬於另一個錢包。',
  FRIEND_ALREADY_EXISTS: '這個錢包已經在好友清單中。',
  INSUFFICIENT_MATERIAL: '素材數量不足。',
  INTERNAL_SERVER_ERROR: '伺服器發生錯誤，請稍後再試。',
  INVALID_REQUEST: '請求內容不正確，請確認選擇後再試。',
  INVALID_AUTH_CHALLENGE: '錢包簽名請求不一致，請重新嘗試。',
  INVALID_AUTH_TOKEN: '登入狀態已過期，請重新登入。',
  INVALID_SIGNATURE: '錢包簽名驗證失敗，請重新嘗試。',
  INVALID_TOKEN: '登入狀態已過期，請重新登入。',
  PET_NOT_OWNED: '選擇的角色不在目前錢包資料中，請重新整理角色。',
  PETS_LOOKUP_FAILED: '角色資料檢查失敗，請稍後再試。',
  LISTING_NOT_ACTIVE: '這件商品已不是有效掛單，請重新整理市場。',
  MARKET_LISTING_BUY_CONFLICT: '購買時商品狀態已變更，請重新整理市場後再試。',
  MARKET_LISTING_CANCEL_CONFLICT: '下架時商品狀態已變更，請重新整理市場後再試。',
  MARKET_LISTING_CREATE_FAILED: '商品上架失敗，請稍後再試。',
  MARKET_LISTING_NOT_FOUND: '這件商品已不存在，請重新整理市場。',
  MARKET_LISTING_NOT_OWNED: '只能下架自己的商品。',
  MARKET_LISTINGS_LOOKUP_FAILED: '市場商品載入失敗，請稍後再試。',
  MATERIAL_LISTING_NOT_FOUND: '這件商品已不存在，請重新整理市場。',
  NETWORK_ERROR: '無法連線到後端服務，請確認伺服器已啟動。',
  PLAYER_NOT_FOUND: '找不到玩家資料，請重新登入。',
  PET_LISTING_NOT_FOUND: '這件角色商品已不存在，請重新整理市場。',
  PET_NOT_FOUND: '找不到這隻角色。',
  TRANSACTION_CREATE_FAILED: '市場操作已完成，但交易紀錄儲存失敗，請重新整理。',
  TRANSACTIONS_LOOKUP_FAILED: '交易紀錄載入失敗，請稍後再試。',
  VALIDATION_ERROR: '請求內容不正確，請確認選擇後再試。',
  WALLET_PROVIDER_MISSING: '尚未安裝或啟用錢包，請先開啟錢包後繼續。',
  WALLET_SIGNATURE_FAILED: '錢包簽名失敗，請重新嘗試。',
  WALLET_TRANSACTION_FAILED: '錢包交易失敗，請重新嘗試。',
}

export function translateApiError(error: unknown, fallback: string) {
  console.error('Frontend API Error:', error)
  const code = error instanceof Error ? error.message : ''
  const messages = locale.value === 'zh-TW' ? zhApiErrorMessages : apiErrorMessages

  if (code && messages[code]) {
    return messages[code]
  }

  if (locale.value === 'zh-TW') {
    return fallback && !/[A-Za-z_]/.test(fallback) ? fallback : '操作失敗，請稍後再試。'
  }

  return code || fallback
}
