export const cryptoPetsAbi = [
  'function addPet(string petName, address to, uint8 _petIv) returns (bool)',
  'function addCloth(uint8 clothId, address to, uint256 _petId) returns (bool)',
  'function setPetLevel(uint256 _petId, uint256 level) returns (bool)',
  'function approve(address to, uint256 tokenId)',
  'function balanceOf(address petOwner) view returns (uint256)',
  'function buyPet(uint256 tokenId) payable returns (bool)',
  'function cancelPetListing(uint256 tokenId) returns (bool)',
  'function getApproved(uint256 tokenId) view returns (address)',
  'function getPet(uint256 _petId) view returns (tuple(uint256 petId, string petName, uint8 petIv, uint256 petLevel, uint8 petSkin))',
  'function getPetAttribute(uint256 _petId) view returns (uint256, string, uint8, uint256, uint8)',
  'function getTotalPet() view returns (uint256)',
  'function getUserPetId(address who) view returns (uint256[])',
  'function isApprovedForAll(address account, address operator) view returns (bool)',
  'function listPet(uint256 tokenId, uint256 price) returns (bool)',
  'function owner() view returns (address)',
  'function ownerOf(uint256 tokenId) view returns (address)',
  'function ownerToPets(address, uint256) view returns (uint256 petId, string petName, uint8 petIv, uint256 petLevel, uint8 petSkin)',
  'function petId() view returns (uint256)',
  'function petListings(uint256) view returns (address seller, uint256 price)',
  'function safeTransferFrom(address from, address to, uint256 tokenId)',
  'function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)',
  'function sellCloth(uint8 clothId, address from, address to, uint256 fromPetId, uint256 toPetId) returns (bool)',
  'function setApprovalForAll(address operator, bool approved)',
  'function supportsInterface(bytes4 interfaceId) view returns (bool)',
  'function transferFrom(address from, address to, uint256 tokenId)',
  'event PetListed(uint256 indexed tokenId, address indexed seller, uint256 price)',
  'event PetListingCanceled(uint256 indexed tokenId)',
  'event PetBought(uint256 indexed tokenId, address indexed seller, address indexed buyer, uint256 price)'
]

export const cryptoMaterialsAbi = [
  'function balanceOf(address account, uint256 materialId) view returns (uint256)',
  'function balanceOfBatch(address[] accounts, uint256[] ids) view returns (uint256[])',
  'function buyMaterial(uint256 listingId) payable returns (bool)',
  'function cancelMaterialListing(uint256 listingId) returns (bool)',
  'function decreaseMaterial(address from, uint256 materialId, uint256 amount) returns (bool)',
  'function increaseMaterial(address to, uint256 materialId, uint256 amount) returns (bool)',
  'function isApprovedForAll(address account, address operator) view returns (bool)',
  'function listMaterial(uint256 materialId, uint256 amount, uint256 price) returns (uint256)',
  'function materialListingId() view returns (uint256)',
  'function materialListings(uint256) view returns (address seller, uint256 materialId, uint256 amount, uint256 price, bool active)',
  'function mintMaterial(address to, uint256 materialId, uint256 amount) returns (bool)',
  'function owner() view returns (address)',
  'function safeBatchTransferFrom(address from, address to, uint256[] ids, uint256[] amounts, bytes data)',
  'function safeTransferFrom(address from, address to, uint256 id, uint256 amount, bytes data)',
  'function setApprovalForAll(address operator, bool approved)',
  'function supportsInterface(bytes4 interfaceId) view returns (bool)',
  'event MaterialListed(uint256 indexed listingId, address indexed seller, uint256 indexed materialId, uint256 amount, uint256 price)',
  'event MaterialListingCanceled(uint256 indexed listingId)',
  'event MaterialBought(uint256 indexed listingId, address indexed seller, address indexed buyer, uint256 materialId, uint256 amount, uint256 price)'
]
